print("Ejemplo de listas")
arcoiris=["verde","azul","morado"]
print(arcoiris)
longitud=len(arcoiris)
print("Elemento que contiene la lista arcoiris ", longitud)
print(f"Elemento que contiene la lista arcoiris v2  {longitud}")
print("accediendo a un elemento de la lista")
print(arcoiris[1])
print(f"elemento en la posicion 0 es {arcoiris[0]}")
print(f"El primer color del arcoiris es:",arcoiris[0])
print("agregar a un elemento de la lista")
print(arcoiris)
arcoiris.append("naranja")
print(arcoiris)
print("Listar los elemntos de la lista ciclo for")
for Angel in arcoiris:
    print(Angel)